### PR TITLE
Expose GDAL debug message via the PgSQL logging system

### PR DESCRIPTION
**Pull request by pramsey**
This adds the PgSQL log system into GDAL error messages via the callback setup. GDAL messages are logged at DEBUG2 level.

### CODE REVIEW

**Comment by pramsey** [comment]
@robe2 I would be interested in your thoughts on this.

**Comment by robe2** [comment]
@pramsey  On surface looks okay.  To enable it I presume in addition to adding it to config options, you need to do

`set client_min_messages=DEBUG2;`

That seems to be missing from your  instruction, or is that not needed?

I would also not fold in the  `CPL_DEBUG=ON` with your original example as there is no explanation of it so people will just copy and paste it thinking its part of the whole LATIN encoding piece.

It really should be a separate section like

How to debug FDW issues, and then you go into detail about adding in the extra CPL_DEBUG

I'll give it a try in a bit.

**Comment by pramsey** [comment]
There is a separate "debug" section in the README and it does mention client_min_messages, so we're good there.

**Comment by robe2** [comment]
@pramsey  hah you added that after I looked.  Very sneaky :)

@dwadler  Does Paul's instructions make sense.  I still haven't gotten chance to rebuild and test.  Got side-tracked with other tasks.

**Comment by robe2** [comment]
@pramsey looks good to me.  I'd commit.

With ODBC driver I get debug info such as:

> DEBUG:  [0] OGR_ODBC: Table dbo.Billing has no identified FID column.

**Comment by pramsey** [comment]
Seems like good info to have!

**Pull request merged**
